# Generated by Django 6.1.1 on 2026-09-13 02:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='categorias_interes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('banco', models.CharField(choices=[('GRINGOTTS', 'Gringotts Wizarding Bank'), ('GOLIATH', 'Goliath National Bank'), ('BANKS_BANK', "Bank's Bank")], max_length=20)),
                ('numero_cuenta', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El número de cuenta debe tener el formato xxx-xxxx-xxxx.', regex='^\\d{3}-\\d{4}-\\d{4}$')])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
