# Generated by Django 6.1.1 on 2026-09-13 04:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriainteres_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('TRANSFERENCIA_INTERNA', 'Transferencia interna'), ('TRANSFERENCIA_EXTERNA', 'Transferencia externa')], max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_hora', models.DateTimeField()),
                ('origen_nombre', models.CharField(blank=True, max_length=150)),
                ('origen_apellido', models.CharField(blank=True, max_length=150)),
                ('origen_numero_cuenta', models.CharField(blank=True, max_length=13)),
                ('destino_nombre', models.CharField(blank=True, max_length=150)),
                ('destino_apellido', models.CharField(blank=True, max_length=150)),
                ('destino_numero_cuenta', models.CharField(blank=True, max_length=13)),
                ('destino_banco', models.CharField(blank=True, max_length=20)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='core.contacto')),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_destino', to='core.cuenta')),
                ('cuenta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_origen', to='core.cuenta')),
            ],
        ),
    ]
