# Generated by Django 6.1.1 on 2026-09-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='banco',
            field=models.CharField(choices=[('GRINGOTTS', 'Gringotts Wizarding Bank'), ('GOLIATH', 'Goliath National Bank'), ('BANKS_BANK', "Bank's Bank")], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='destino_banco',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
