# Generated by Django 6.1.1 on 2026-09-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contacto_banco_alter_transaccion_destino_banco'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaccion',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='transaccion_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='transaccion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contacto__isnull', True), ('cuenta_destino__isnull', True), ('cuenta_origen__isnull', True), ('tipo', 'DEPOSITO')), models.Q(('contacto__isnull', True), ('cuenta_destino__isnull', False), ('cuenta_origen__isnull', False), ('tipo', 'TRANSFERENCIA_INTERNA')), models.Q(('contacto__isnull', False), ('cuenta_destino__isnull', True), ('cuenta_origen__isnull', False), ('tipo', 'TRANSFERENCIA_EXTERNA')), _connector='OR'), name='transaccion_combinacion_valida'),
        ),
    ]
