# Generated by Django 6.1.1 on 2026-09-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaccion_transaccion_monto_positivo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaccion',
            name='transaccion_combinacion_valida',
        ),
        migrations.AddConstraint(
            model_name='transaccion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contacto__isnull', True), ('cuenta_destino__isnull', False), ('cuenta_origen__isnull', True), ('tipo', 'DEPOSITO')), models.Q(('contacto__isnull', True), ('cuenta_destino__isnull', False), ('cuenta_origen__isnull', False), ('tipo', 'TRANSFERENCIA_INTERNA')), models.Q(('contacto__isnull', False), ('cuenta_destino__isnull', True), ('cuenta_origen__isnull', False), ('tipo', 'TRANSFERENCIA_EXTERNA')), _connector='OR'), name='transaccion_combinacion_valida'),
        ),
    ]
