# Generated by Django 6.1.1 on 2026-09-20 20:41

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_transaccion_transaccion_combinacion_valida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INTERNA', 'Transferencia interna'), ('EXTERNA', 'Transferencia externa')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000.00'))])),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado_en', models.DateTimeField()),
                ('expira_en', models.DateTimeField()),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_pendientes_contacto', to='core.contacto')),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_pendientes_destino', to='core.cuenta')),
                ('cuenta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_pendientes_origen', to='core.cuenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_pendientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('contacto__isnull', True), ('cuenta_destino__isnull', False), ('tipo', 'INTERNA')), models.Q(('contacto__isnull', False), ('cuenta_destino__isnull', True), ('tipo', 'EXTERNA')), _connector='OR'), name='transferencia_pendiente_combinacion_valida'), models.CheckConstraint(condition=models.Q(('monto__gte', Decimal('1000.00'))), name='transferencia_pendiente_monto_minimo')],
            },
        ),
    ]
