# Generated by Django 6.1.1 on 2026-09-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transferenciapendiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciapendiente',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
